services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: testDb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 33066:3306
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  mysqldata:
